### PR TITLE
Feature/add gmail

### PR DESCRIPTION
**Pull request by sk364**

### CODE REVIEW

**Comment by MichaelYusko** [comment]
@sk364 a flask server start, correct?

**Comment by sk364** [comment]
> a flask server start, correct?

What do you mean ?

**Comment by MichaelYusko** [comment]
@sk364 I mean, if a flask server starting correctly, try it on examples files. And check please whether we don't have any errors

**Comment by MichaelYusko** [comment]
@sk364

**Comment by sk364** [comment]
@MichaelYusko It's running fine.

**Comment by MichaelYusko** [comment]
@sk364 cool, please fix, conflicts and I will merge.

**Pull request merged**
